### ISSUE TITLE
Should there be a __destruct() method that closes the connection if it's left open?

### ISSUE THREAD

**Issue by scottchiefbaker** [BenMenking/routeros-api#1]
For consistency we should probably always close the connection. Should we have a destructor that does this automatically?

**Comment by BenMenking** [comment]
Technically speaking, PHP will close the connection when the script
completes.  But you've brought up a very valid question in a situation
where the routeros-api object was created and then unset at a later point
in the script.  For long running scripts and in this scenario the socket
would still be open (and possibly timeout) but for clarity and
completeness, I think it's a great idea.



Ben Menking
*IT Security Consulting*
*ben@infotechsc.com <ben@infotechsc.com>*
Phone: 864.420.5603

**Comment by scottchiefbaker** [comment]
Ben merged it...
