### ISSUE TITLE
Call to undefined method RouterosAPI::parse_response()

### ISSUE THREAD

**Issue by src386** [BenMenking/routeros-api#10]
Hi,
When I execute example1.php, I get results from the router so the connection is okay.
However, data is not parsed : 

    Call to undefined method RouterosAPI::parse_response()

Thanks.

**Comment by exmac** [comment]
fixed on https://github.com/BenMenking/routeros-api/pull/11
or just use function: parseResponse

**Comment by src386** [comment]
PHP Warning:  preg_match_all() expects parameter 2 to be string, array given in /home/xavier/routeros-api/routeros_api.class.php on line 171

(with ParseReponse).

**Comment by exmac** [comment]
yes, looks like it was parsed by function read

**Comment by exmac** [comment]
https://github.com/BenMenking/routeros-api/pull/12
check this

**Comment by exmac** [comment]
in any way better use ->comm

**Comment by src386** [comment]
I gave another try, it's working with parseReponse.
Thanks.

**Comment by scottchiefbaker** [comment]
@src386 if this is working for you with the last commits please close this issue.

**Comment by src386** [comment]
thanks
