### ISSUE TITLE
Cannot add new user for version 6.3++

### ISSUE THREAD

**Issue by adifaidz** [BenMenking/routeros-api#22]
This code was working for v6.2, but for some reason, it didnt for 6.37. 
```
  $ARR=$this->API->createUserAndProfile(Array(
     "customer" => "admin",
     "name" => ("$username$postfix"),
     "password" => ("$username$postfix"),
     "numbers" => ("$username$postfix"),
     "profile" => $value,
  ));

  public function createUser(Array $data)
  {
    $this->comm("/tool/user-manager/user/add", $data);
  }

  public function createProfile(Array $data)
  {
    $this->comm("/tool/user-manager/user/create-and-activate-profile", $data);
  }

  public function createUserAndProfile(Array $data){
    $this->createUser(array_except($data, ['numbers', 'profile']));
    $this->createProfile(array_except($data, ['name', 'password']));
  }
```

This is the response message I got on 6.3+ was `unknown parameter`. Please help me in need of solution here 😢 🙏

**Comment by Mikki-10** [comment]
Not sure what type of user that is you try to make?
But try:

$API->write('/user/add
							=name='.$username.'
							=password='.$password.'
							=group='.$group.'
							=address='.$address.'
							=disabled='.$disabled.'
							=comment='.$comment);

**Comment by BenMenking** [comment]
Going to close this if it's not an issue....
