### ISSUE TITLE
Composer Packages?

### ISSUE THREAD

**Issue by juliardi** [BenMenking/routeros-api#25]
I can't find this project on packagist. There are many similar project on routeros-api, but as far as I know this project has the latest update and one that is working. 
So, could you register this project on packagist?

**Comment by BenMenking** [comment]
Can't register it.  Packagist complains about uppercase characters in the URL.

**Comment by juliardi** [comment]
Could you rename the `name` section in the `composer.json` to `benmenking/routeros-api` and try again?
