### ISSUE TITLE
How to add breaklines when Sent SMS API

### ISSUE THREAD

**Issue by muhammad-ihsan** [BenMenking/routeros-api#37]
Good morning,
i have some problem adding breakline into my mikrotik API for sending a message. I already try to use `PHP_EOL`, `\n`, `\r\n`. There is no luck, the message only prints first line of the message.

Here is my code:
```
$mikrokit->comm("/tool/sms/send",array(
    "port"         => "usb1",
    "channel"      => "0",
    "phone-number" => $order->order_phone,
    "message"      => "[Rakki] Your order detail".PHP_EOL." Origin: ".$order->origin." ".PHP_EOL."Destination: ".$order->destination"
));
```

[See Mikrotik Documentation](https://wiki.mikrotik.com/wiki/Manual:Tools/Sms)

**Comment by Chupaka** [comment]
Looks like the reason is here: https://github.com/BenMenking/routeros-api/blob/master/routeros_api.class.php#L371

**write** function splits each param by lines and sends them as separate commands :(

**Comment by Chupaka** [comment]
Try to replace `$data = explode("\n", $command);` with `$data = [ $command ];` and recheck. If you're  not using `write` for sending multiple commands as one multiline string - it should work for you.

**Comment by muhammad-ihsan** [comment]
@Chupaka  you are totally right. Thank you for the advice. I will recheck and try to fix this soon.
