### ISSUE TITLE
Problem with RouterOS version 6.45.1

### ISSUE THREAD

**Issue by michnzee** [BenMenking/routeros-api#42]
Hello, after upgrade RouterOS 6.45.1 the PHP api class stop working because there is some changes in login procedure - via [https://wiki.mikrotik.com/wiki/Manual:API#Initial_login](url) - a lot of admin communities stop working their management scripts and it's reported in mikrotik official forum. It's possible to modify login procedure?
Log info: _system, error, critical: login failed for user myAPI from ipaddress via api._
Thank you

**Comment by michnzee** [comment]
Aaahh... so, I upgrade latest version routeros-api class where is fix (api login above ros 6.43+) and there is all fixed. My shame :( Working good :)

**Comment by ezechinwa** [comment]
> Aaahh... so, I upgrade latest version routeros-api class where is fix (api login above ros 6.43+) and there is all fixed. My shame :( Working good :)

Hi, Where can I find the router_api class for this new version

**Comment by Chupaka** [comment]
> Hi, Where can I find the router_api class for this new version

It's right here, in this repo: https://github.com/BenMenking/routeros-api/blob/master/routeros_api.class.php

**Comment by Chupaka** [comment]
> so, I upgrade latest version routeros-api class where is fix (api login above ros 6.43+) and there is all fixed
It was fixed a year ago, BTW :)
Please close the issue
