### ISSUE TITLE
Access RB via Mac Address

### ISSUE THREAD

**Issue by m4v0** [BenMenking/routeros-api#49]
Hi Ben!!

Is it possible to connect to RB via MAC address ?? with the Routers API.

I need to access RB via MAC to create the first configurations, without the intervention of a technician. This process would be one time, when registering a new RB on the WEB platform that I am creating ....

**Comment by Chupaka** [comment]
It's not possible as API works over TCP. There's no such thing as MAC API :(

**Comment by m4v0** [comment]
thank you man! Is there any solution with another language?

**Comment by pchf3788** [comment]
How about Python? Should be able to solve it!



我没有天使那样虚伪，也没有死神那么慈悲


&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Marcelo Olate"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月14日(星期六) 中午12:37
收件人:&nbsp;"BenMenking/routeros-api"<routeros-api@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [BenMenking/routeros-api] Access RB via Mac Address (#49)




thank you man! Is there any solution with another language?
