### ISSUE TITLE
how to print torch data

### ISSUE THREAD

**Issue by fat-so** [BenMenking/routeros-api#53]
i try to print torch data
i can successfully do this on mikrotik terminal
but i can't do this in api
here is my code 
$API->write('/tool/torch=interface=bridge1');
i'm not sure how to do this

**Comment by Chupaka** [comment]
> $API->write('/tool/torch=interface=bridge1');

That command is completely invalid. It should be something like

```
$API->write('/tool/torch', false);
$API->write('=interface=bridge1');
```

Also, make sure you're reading a stream, not just waiting for the whole result, as this command returns the result infinitely (unless =duration=XXX is specified).

**Comment by fat-so** [comment]
Thank you very much
and i want know how to print ip and macAddress on torch 
when i print the stream content , it just printed rx , tx , rx-packets , tx-packets and section number(the section number is useless , it's just like mikrotik make "section++")

**Comment by fat-so** [comment]
> > $API->write('/tool/torch=interface=bridge1');
> 
> That command is completely invalid. It should be something like
> 
> ```
> $API->write('/tool/torch', false);
> $API->write('=interface=bridge1');
> ```
> 
> Also, make sure you're reading a stream, not just waiting for the whole result, as this command returns the result infinitely (unless =duration=XXX is specified).
Thank you very much
and i want know how to print ip and macAddress on torch
when i print the stream content , it just printed rx , tx , rx-packets , tx-packets and section number(the section number is useless , it'

**Comment by fat-so** [comment]
> > $API->write('/tool/torch=interface=bridge1');
> 
> That command is completely invalid. It should be something like
> 
> ```
> $API->write('/tool/torch', false);
> $API->write('=interface=bridge1');
> ```
> 
> Also, make sure you're reading a stream, not just waiting for the whole result, as this command returns the result infinitely (unless =duration=XXX is specified).

is very helpful 
thx
