### ISSUE TITLE
SSL connection

### ISSUE THREAD

**Issue by Ripperua** [BenMenking/routeros-api#54]
SSL CONNECTION DOESNT WORK (TESTED MT 6.48) ...
That writes that it use anonymous Diffie-Hellman cipher should be used to connect... https://wiki.mikrotik.com/wiki/Manual:API-SSL

Can't understand how to fix that ... (without SSL its works)

**Comment by Chupaka** [comment]
So what's the exact error you have?.. What does 'DOESNT WORK' mean? How do you test it?
