### ISSUE TITLE
disabled/enable NAT

### ISSUE THREAD

**Issue by abdkaviani** [BenMenking/routeros-api#57]
Hello
I want to change one of NAT (num3) from enable to disabled,
This is my code:

`$API->write("/ip/firewall/nat/set", false);`
`$API->write("=disabled=yes", false);`
`$API->write("=.id=3");`

What is wrong?
Thank you

**Comment by scottchiefbaker** [comment]
I think you want something like this:

```
$cmd    = "/ip/firewall/nat/set";
$params = ['.id' => 3, 'disabled' => 'yes'];
$data   = $API->comm($cmd, $params);
```
