### ISSUE TITLE
torch not working

### ISSUE THREAD

**Issue by muhammadarsalansiddiqui** [BenMenking/routeros-api#58]
this is my code and its not working.

        $API->write('/tool/torch',false);
        //$API->write("=interface=vlan3212");
        $API->write("=interface=".$rb_interface);
        $API->write("=src-address=".$rb_ip);
        $ARRAY= $API->read(false);
        print_r($ARRAY);

output:

Connection attempt #1 to 10.0.1.1:5891... <<< [6] /login <<< [13] =name=username_api<<< [26] =password=password_api >>> [5/5] bytes read. >>> [5, 1]!done Connected... <<< [11] /tool/torch <<< [19] =interface=vlan3212 <<< [25] =src-address=10.31.126.21 >>> [5/5] bytes read. >>> [5, 40]!trap >>> [31/31] bytes read. >>> [31, 8]=message=no such command prefix >>> [5/5] bytes read. >>> [5, 1]!done Array ( [0] => !trap [1] => =message=no such command prefix [2] => !done ) Disconnected... Disconnected...

**Comment by Chupaka** [comment]
`$API->write("=interface=".$rb_interface);` should be `$API->write("=interface=".$rb_interface, false);`

**Comment by muhammadarsalansiddiqui** [comment]
I also tries that, but it keeps the page loading.

```
        $API->write('/tool/torch');
        $API->write("=interface=NOC-40G",false);
        $ARRAY= $API->read(false);
        print_r($ARRAY);
```

**Comment by Chupaka** [comment]
1) This should be
```
        $API->write('/tool/torch', false);
        $API->write("=interface=NOC-40G");
```
Are you sure you understand the second parameter?

2) Torch is constantly running command, it produces infinite output. If you need to stop at some point - add duration parameter, like
```
        $API->write('/tool/torch', false);
        $API->write("=interface=NOC-40G", false);
        $API->write("=duration=1s");
```

**Comment by muhammadarsalansiddiqui** [comment]
i also tried to add duration parameter and interchanging false between these two statements

they return command does not exist

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Chupaka** [comment]
Please post exact code and the result.

**Comment by muhammadarsalansiddiqui** [comment]
okay my problem is solved now, it was duration issue, 1s is not giving me results

**Comment by muhammadarsalansiddiqui** [comment]
thank you for your support.

**Comment by Chupaka** [comment]
Please close the issue
