### ISSUE TITLE
SSL API with v6 RouterOS

### ISSUE THREAD

**Issue by scottchiefbaker** [BenMenking/routeros-api#6]
This is an open issue to discuss doing API calls via SSL with newer versions of RouterOS. Is this something we can support?

**Comment by BenMenking** [comment]
I think this is an absolute necessity

**Comment by BenMenking** [comment]
I upgraded one of mine to v6.31 and will work on implementing api-ssl.  Pretty close already, but getting a weird SSL error.

**Comment by scottchiefbaker** [comment]
I haven't even looked at the SSL API. What's involved in get PHP to talk to it?

**Comment by BenMenking** [comment]
Should be as simple as changing the host in the fsockopen call to
"ssl://$hostname" as the fsockopen call will handle the SSL handshake and
negotiation.  Using a client certificate might require some additional work.

Ben Menking
*IT Security Consulting*
*ben@infotechsc.com <ben@infotechsc.com>*
Phone: 864.420.5603

**Comment by scottchiefbaker** [comment]
Is there in any state I can test it?

**Comment by BenMenking** [comment]
Sort-of.  I'm having problems getting it to work properly with my RouterOS.

Ben Menking
*IT Security Consulting*
*ben@infotechsc.com <ben@infotechsc.com>*
Phone: 864.420.5603

**Comment by scottchiefbaker** [comment]
I'm just getting back to this, as we're getting really close to launching MikroTiks for our ISP customers. Where do we stand on API+SSL support?

**Comment by shinradev** [comment]
I have created a pull request that would enable ssl functionality. Thanks.

**Comment by lukemlsna** [comment]
@BenMenking Make sure you've specified a certificate under /IP/Services/ssl-api on your routeros device to properly enable encryption. If you are using a self-signed certificate, you _may_ need to instruct the client to trust that certificate. SSL connection worked for me in testing without having to import anything, but I used a publicly trusted cert. It also worked fine for me using a self-signed certificate on a debian cleint.

**Comment by BenMenking** [comment]
@scottchiefbaker do these code changes help?

**Comment by scottchiefbaker** [comment]
I haven't had a chance to test any of this. As long as we're making progress on it I'm happy.

**Comment by exmac** [comment]
I was just test it, work Fine!

**Comment by BenMenking** [comment]
Let's close this then.  If it becomes an issue, we can reopen.
