### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ntnetx** [BenMenking/routeros-api#67]
English
hello!! Could you ask a question how would you do these 2 executions PHP to use the api tool to execute this command below?

/tool sniffer packet print where protocol=tcp

/tool sniffer packet print where protocol=udp

Portugues

olá!! poderia tirar uma dúvida como faria essas 2 execução PHP para usar a ferramenta da api para executar esse comando abaixo?

/tool sniffer packet print where protocol=tcp

/tool sniffer packet print where protocol=udp

**Comment by ve3** [comment]
Please see [this issue](https://github.com/BenMenking/routeros-api/issues/24), I hope that will work for you.

Edit: ------------
I'll copy the answer in the link to be here to prevent issue deleted. Below is copied from the link above.

> If you would like to use command `where` with `or`, like this one in terminal.
> 
> ```
> /ip dhcp-server lease print where address=192.168.1.11 or address=192.168.1.12 or address=192.168.1.13
> ```
> 
> Here is sample code.
> 
> ```php
> $API->write('/ip/dhcp-server/lease/print', false);
> $API->write('?address=192.168.1.11', false);
> $API->write('?address=192.168.1.12', false);
> $API->write('?#|', false);
> $API->write('?address=192.168.1.13', false);
> $API->write('?#|');
> $result = $API->read();
> // use `$result` variable.
> ```
> 
> See reference from manual [here](https://wiki.mikrotik.com/wiki/Manual:API#Query_word), and [here](https://wiki.mikrotik.com/wiki/Manual:API#Queries).

**Comment by BenMenking** [comment]
Appears answered.
