### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by borsn** [BenMenking/routeros-api#7]
Hello,
Just discovered your script.

I am unable to login...this is what I get with the debugger turned on: `Connection attempt #1 to 192.168.1.1:8728... Connection attempt #2 to 192.168.1.1:8728... Connection attempt #3 to 192.168.1.1:8728... Connection attempt #4 to 192.168.1.1:8728... Connection attempt #5 to 192.168.1.1:8728... Error... Disconnected...`

Am I doing something wrong?

Thx

**Comment by scottchiefbaker** [comment]
That looks like a firewall problem to me? Are you able to `telnet to 192.168.1.1 8278` or do you immediately get connection refused?

**Comment by BenMenking** [comment]
Closing due to age.  Reopen if this is still an issue.
