### ISSUE TITLE
Infinity Loop on Fetch Command

### ISSUE THREAD

**Issue by deivisonmoraes** [BenMenking/routeros-api#9]
Gentlemen,
I'm using the API to perform the backup router. At the time of using the fetch command to send via ftp in version 5.26 enters an infinite loop response like this:
<<< [11] / tool / fetch
<<< [22] = IPv4 address =
<<< [9] = mode = ftp
<<< [31] = src-path = 10.7.3.46--26-Nov.src
<<< [20] = user = mikrotik backup
<<< [19] = password = siria 2015
<<< [11] = upload = yes
<<< [41] = dst-path = 10.7.3.46 / 10.7.3.46--26-Nov.rsc

> > > [3/3] bytes read.
> > > [3, 20]! Re
> > > [18/18] bytes read.
> > > [18, 1] = connecting status =
> > > [3/3] bytes read.
> > > [3, 18]! Re
> > > [16/16] bytes read.
> > > [16, 1] = status = finished
> > > [3/3] bytes read.
> > > [3, 18]! Re
> > > [16/16] bytes read.
> > > [16, 1] = status = finished
> > > [3/3] bytes read.
> > > [3, 18]! Re
> > > [16/16] bytes read.
> > > [16, 1] = status = finished
> > > [3/3] bytes read.
> > > [3, 18]! Re
> > > [16/16] bytes read.
> > > [16, 1] = status = finished
> > > This only occurs in versions 5.XX. In version 6 it works correctly.
> > > Thank you.

Follows the command line api:

$api->comm("/tool/fetch", array(
                'address' => '111.111.111.111',
                'mode'    => 'ftp',
                'src-path'=> "$arquivo_backup_nome.rsc",
                'user'    => 'backupmikrotik',
                'password'=> 'siria2015',
                'upload'  => 'yes',
                'dst-path'=> "$ipv4/$arquivo_backup_nome.rsc"
        ));

**Comment by BenMenking** [comment]
I have a 5.25 and from a terminal an upload goes on until it stops after a couple minutes with:

```
status: failed
failure: Unrecognized FTP server response: 426 Connection timed out, aborting tran
sfer
421 Connection timed out.
```

I'm going to chalk this one up as a Mikrotik issue.  Guess they solved it in v6.
